[package]
name = "chef"
version = "0.0.0"
edition = "2021"

[profile.release]
debug = true

[features]
debug_trace = []
debug_code = []

[dependencies]
thiserror = "1.0.64"
gc-arena = "0.5.3"

[dev-dependencies]
regex = "1.11.0"
test-generator = "0.3.1"