[package]
name = "chef"
version = "0.0.0"
edition = "2021"

[features]
debug_trace = []
debug_trace_gc = []

[dependencies]
thiserror = "1.0.64"

[dev-dependencies]
regex = "1.11.0"
test-generator = "0.3.1"